-- S10: bounded broadcast repetitions and pending-order backlog episodes.
-- Apply after 20260909_06_notification_acknowledgement.sql.
ALTER TABLE `NOTIFICATION_DELIVERIES`
    ADD COLUMN IF NOT EXISTS `OCCURRENCE_NO` TINYINT NOT NULL DEFAULT 1 AFTER `EXPIRES_AT`;

ALTER TABLE `NOTIFICATION_DELIVERIES`
    ADD COLUMN IF NOT EXISTS `EPISODE_ID` VARCHAR(100) NULL AFTER `OCCURRENCE_NO`;

ALTER TABLE `NOTIFICATION_DELIVERIES`
    ADD KEY IF NOT EXISTS `IX_NOTIFICATION_OCCURRENCE`
        (`SOURCE_KEY`,`RECIPIENT_ACCOUNT_ID`,`OCCURRENCE_NO`);

ALTER TABLE `NOTIFICATION_DELIVERY_MATCHES`
    ADD COLUMN IF NOT EXISTS `REPEAT_INTERVAL_MINUTES` SMALLINT NOT NULL DEFAULT 0 AFTER `REQUIRES_ACK`;

ALTER TABLE `NOTIFICATION_DELIVERY_MATCHES`
    ADD COLUMN IF NOT EXISTS `MAX_OCCURRENCES` TINYINT NOT NULL DEFAULT 1 AFTER `REPEAT_INTERVAL_MINUTES`;

CREATE TABLE IF NOT EXISTS `NOTIFICATION_REPEAT_INSTANCES` (
    `DELIVERY_ID` VARCHAR(40) NOT NULL,
    `MATCH_KEY` VARCHAR(160) NOT NULL,
    `SOURCE_KEY` VARCHAR(100) NOT NULL,
    `SOURCE_TYPE` VARCHAR(60) NOT NULL,
    `SOURCE_ID` VARCHAR(100) NULL,
    `EPISODE_ID` VARCHAR(100) NULL,
    `INTERVAL_MINUTES` SMALLINT NOT NULL,
    `OCCURRENCE_NO` TINYINT NOT NULL DEFAULT 1,
    `MAX_OCCURRENCES` TINYINT NOT NULL DEFAULT 1,
    `NEXT_AT` DATETIME(6) NULL,
    `STATUS` VARCHAR(24) NOT NULL DEFAULT 'pending',
    `STOP_REASON` VARCHAR(80) NULL,
    `CREATED_AT` DATETIME(6) NOT NULL,
    `UPDATED_AT` DATETIME(6) NOT NULL,
    PRIMARY KEY (`DELIVERY_ID`,`MATCH_KEY`),
    KEY `IX_NOTIFICATION_REPEAT_DUE` (`STATUS`,`NEXT_AT`),
    CONSTRAINT `FK_NOTIFICATION_REPEAT_DELIVERY`
        FOREIGN KEY (`DELIVERY_ID`) REFERENCES `NOTIFICATION_DELIVERIES` (`ID`)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `NOTIFICATION_BACKLOG_EPISODES` (
    `EPISODE_ID` VARCHAR(100) NOT NULL,
    `RULE_ID` VARCHAR(100) NOT NULL,
    `RULE_REVISION` BIGINT NOT NULL DEFAULT 1,
    `RULE_FINGERPRINT` CHAR(64) NOT NULL,
    `THRESHOLD` INT NOT NULL,
    `REQUIRED_DURATION_MINUTES` SMALLINT NOT NULL,
    `PENDING_COUNT` INT NOT NULL DEFAULT 0,
    `FIRST_SEEN_AT` DATETIME(6) NOT NULL,
    `LAST_SEEN_AT` DATETIME(6) NOT NULL,
    `ACTIVATED_AT` DATETIME(6) NULL,
    `OCCURRENCE_NO` TINYINT NOT NULL DEFAULT 0,
    `STATUS` VARCHAR(24) NOT NULL DEFAULT 'watching',
    `CREATED_AT` DATETIME(6) NOT NULL,
    `UPDATED_AT` DATETIME(6) NOT NULL,
    PRIMARY KEY (`EPISODE_ID`),
    KEY `IX_NOTIFICATION_BACKLOG_STATUS` (`STATUS`,`LAST_SEEN_AT`),
    KEY `IX_NOTIFICATION_BACKLOG_RULE` (`RULE_ID`,`RULE_REVISION`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
