-- S03: bounded retry and quarantine state for the existing notification outbox.
-- Apply this migration before enabling the notification worker.
ALTER TABLE `NOTIFICATION_OUTBOX`
    ADD COLUMN IF NOT EXISTS `ATTEMPTS` INT NOT NULL DEFAULT 0 AFTER `PROCESSED_AT`;

ALTER TABLE `NOTIFICATION_OUTBOX`
    ADD COLUMN IF NOT EXISTS `NEXT_ATTEMPT_AT` DATETIME(6) NULL AFTER `ATTEMPTS`;

ALTER TABLE `NOTIFICATION_OUTBOX`
    ADD COLUMN IF NOT EXISTS `LAST_ERROR` VARCHAR(1000) NULL AFTER `NEXT_ATTEMPT_AT`;

ALTER TABLE `NOTIFICATION_OUTBOX`
    ADD COLUMN IF NOT EXISTS `IS_QUARANTINED` TINYINT(1) NOT NULL DEFAULT 0 AFTER `LAST_ERROR`;

ALTER TABLE `NOTIFICATION_OUTBOX`
    ADD COLUMN IF NOT EXISTS `QUARANTINED_AT` DATETIME(6) NULL AFTER `IS_QUARANTINED`;

ALTER TABLE `NOTIFICATION_OUTBOX`
    ADD KEY IF NOT EXISTS `IX_NOTIFICATION_RETRY` (`PROCESSED_AT`,`IS_QUARANTINED`,`NEXT_ATTEMPT_AT`,`CREATED_AT`);
