-- Run once after backing up GUESTBOOK_COMMENTS and GUESTBOOK_REPLIES.
-- Additive migration; legacy comments/replies remain customer-authored.
ALTER TABLE `GUESTBOOK_COMMENTS`
  MODIFY COLUMN `CREATED_AT` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  ADD COLUMN `ALLOW_REPLIES` BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN `AUTHOR_TYPE` VARCHAR(24) NOT NULL DEFAULT 'customer',
  ADD COLUMN `AUTHOR_ADMIN_ID` VARCHAR(40) NULL,
  ADD COLUMN `AUTHOR_STAFF_ID` VARCHAR(40) NULL,
  ADD COLUMN `EDITED_AT` DATETIME(6) NULL,
  ADD COLUMN `VERSION` INT NOT NULL DEFAULT 1,
  ADD INDEX `IX_GUESTBOOK_PUBLIC` (`IS_VISIBLE`, `IS_PINNED`, `CREATED_AT`, `ID`);
ALTER TABLE `GUESTBOOK_REPLIES`
  MODIFY COLUMN `CREATED_AT` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  ADD COLUMN `AUTHOR_TYPE` VARCHAR(24) NOT NULL DEFAULT 'customer',
  ADD COLUMN `AUTHOR_ADMIN_ID` VARCHAR(40) NULL,
  ADD COLUMN `AUTHOR_STAFF_ID` VARCHAR(40) NULL,
  ADD COLUMN `EDITED_AT` DATETIME(6) NULL,
  ADD COLUMN `VERSION` INT NOT NULL DEFAULT 1,
  ADD INDEX `IX_GUESTBOOK_REPLY_PAGE` (`COMMENT_ID`, `IS_VISIBLE`, `CREATED_AT`, `ID`);
CREATE TABLE `GUESTBOOK_AUDIT_LOG` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `THREAD_ID` VARCHAR(40) NOT NULL,
  `MESSAGE_ID` VARCHAR(40) NOT NULL,
  `ACTOR_ID` VARCHAR(40) NOT NULL,
  `ACTION` VARCHAR(32) NOT NULL,
  `BEFORE_VALUE` JSON NULL,
  `AFTER_VALUE` JSON NULL,
  `CREATED_AT` DATETIME(6) NOT NULL,
  INDEX `IX_GUESTBOOK_AUDIT_THREAD` (`THREAD_ID`, `CREATED_AT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `GUESTBOOK_COOLDOWNS` (
  `VISITOR_KEY` CHAR(64) NOT NULL PRIMARY KEY,
  `NEXT_ALLOWED_AT` DATETIME(6) NOT NULL,
  INDEX `IX_GUESTBOOK_COOLDOWN_EXPIRY` (`NEXT_ALLOWED_AT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `GUESTBOOK_SETTINGS` (
  `ID` INT NOT NULL PRIMARY KEY,
  `MASCOT_NAME` VARCHAR(60) NOT NULL,
  `VERSION` INT NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO `GUESTBOOK_SETTINGS` (`ID`, `MASCOT_NAME`) VALUES (1, '吉祥物');
