-- S09: acknowledgement, withdrawal and source-level receipt state.
-- Apply after 20260909_05_notification_schedules.sql and before enabling S09 APIs.
ALTER TABLE `NOTIFICATION_DELIVERIES`
    ADD COLUMN IF NOT EXISTS `ACKNOWLEDGED_AT` DATETIME(6) NULL AFTER `READ_AT`;

ALTER TABLE `NOTIFICATION_DELIVERIES`
    ADD COLUMN IF NOT EXISTS `WITHDRAWN_AT` DATETIME(6) NULL AFTER `ACKNOWLEDGED_AT`;

ALTER TABLE `NOTIFICATION_DELIVERIES`
    ADD KEY IF NOT EXISTS `IX_NOTIFICATION_ACKNOWLEDGEMENT`
        (`RECIPIENT_ACCOUNT_ID`,`ACKNOWLEDGED_AT`,`WITHDRAWN_AT`,`EXPIRES_AT`);

-- One delivery may contain personal and broadcast matches.  Keeping the
-- source rows separately lets a manager withdraw one broadcast without
-- deleting the personal part of the merged delivery.
CREATE TABLE IF NOT EXISTS `NOTIFICATION_DELIVERY_MATCHES` (
    `DELIVERY_ID` VARCHAR(40) NOT NULL,
    `MATCH_KEY` VARCHAR(160) NOT NULL,
    `SOURCE_KEY` VARCHAR(100) NOT NULL,
    `SOURCE_TYPE` VARCHAR(60) NOT NULL,
    `SOURCE_ID` VARCHAR(100) NULL,
    `OWNER_KEY` VARCHAR(90) NOT NULL,
    `RULE_ID` VARCHAR(100) NOT NULL,
    `RULE_TYPE` VARCHAR(60) NOT NULL,
    `RULE_REVISION` BIGINT NOT NULL DEFAULT 1,
    `RULE_FINGERPRINT` CHAR(64) NOT NULL,
    `POPUP_MODE` VARCHAR(24) NOT NULL,
    `SOUND_ID` VARCHAR(40) NULL,
    `PRIORITY` VARCHAR(16) NOT NULL DEFAULT 'normal',
    `EXPIRES_AFTER_MINUTES` SMALLINT NOT NULL DEFAULT 15,
    `IS_BROADCAST` TINYINT(1) NOT NULL DEFAULT 0,
    `REQUIRES_ACK` TINYINT(1) NOT NULL DEFAULT 0,
    `ACKNOWLEDGED_AT` DATETIME(6) NULL,
    `WITHDRAWN_AT` DATETIME(6) NULL,
    `CREATED_AT` DATETIME(6) NOT NULL,
    PRIMARY KEY (`DELIVERY_ID`,`MATCH_KEY`),
    KEY `IX_NOTIFICATION_MATCH_SOURCE`
        (`SOURCE_ID`,`IS_BROADCAST`,`WITHDRAWN_AT`),
    KEY `IX_NOTIFICATION_MATCH_RECEIPT`
        (`DELIVERY_ID`,`REQUIRES_ACK`,`ACKNOWLEDGED_AT`,`WITHDRAWN_AT`),
    CONSTRAINT `FK_NOTIFICATION_MATCH_DELIVERY`
        FOREIGN KEY (`DELIVERY_ID`) REFERENCES `NOTIFICATION_DELIVERIES` (`ID`)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
