-- Stage 3 additive attendance events. Historical settlement inputs remain intact;
-- events provide a replay-safe source for new clock and correction operations.
CREATE TABLE IF NOT EXISTS `STAFF_ATTENDANCE_EVENTS` (
    `ID` VARCHAR(36) NOT NULL,
    `STAFF_MEMBER_ID` VARCHAR(36) NOT NULL,
    `BUSINESS_DATE` DATE NOT NULL,
    `DUTY_PLAN_ID` VARCHAR(36) NULL,
    `EVENT_TYPE` VARCHAR(32) NOT NULL,
    `EVENT_AT` DATETIME(6) NOT NULL,
    `EVENT_END_AT` DATETIME(6) NULL,
    `SOURCE` VARCHAR(24) NOT NULL,
    `MINUTES_DELTA` INT NOT NULL DEFAULT 0,
    `BASE_EVENT_ID` VARCHAR(36) NULL,
    `OPERATION_ID` VARCHAR(36) NOT NULL,
    `REASON` VARCHAR(500) NULL,
    `CREATED_AT` DATETIME(6) NOT NULL,
    `CREATED_BY` VARCHAR(36) NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UX_STAFF_ATTENDANCE_OPERATION` (`OPERATION_ID`),
    KEY `IX_STAFF_ATTENDANCE_STAFF_DATE` (`STAFF_MEMBER_ID`, `BUSINESS_DATE`, `EVENT_AT`),
    KEY `IX_STAFF_ATTENDANCE_PLAN` (`DUTY_PLAN_ID`, `EVENT_TYPE`),
    KEY `IX_STAFF_ATTENDANCE_BASE` (`BASE_EVENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `STAFF_DUTY_PLANS`
    ADD COLUMN IF NOT EXISTS `CROSS_MIDNIGHT` TINYINT(1) NOT NULL DEFAULT 0;
