-- Settlement detail rules: attendance provenance, backfill approval, and audit data.
-- Additive only. Apply before deploying the matching API build.

ALTER TABLE `SETTLEMENT_STAFF_INPUTS`
    ADD COLUMN `ATTENDANCE_SOURCE` VARCHAR(24) NOT NULL DEFAULT 'manual' AFTER `ACTUAL_MINUTES`,
    ADD COLUMN `ATTENDANCE_REQUEST_ID` VARCHAR(36) NULL AFTER `ATTENDANCE_SOURCE`,
    ADD COLUMN `ATTENDANCE_APPROVED_BY` VARCHAR(36) NULL AFTER `ATTENDANCE_REQUEST_ID`,
    ADD COLUMN `ATTENDANCE_APPROVED_AT` DATETIME NULL AFTER `ATTENDANCE_APPROVED_BY`;

CREATE TABLE IF NOT EXISTS `SETTLEMENT_ATTENDANCE_BACKFILL_REQUESTS` (
    `ID` VARCHAR(36) NOT NULL,
    `SETTLEMENT_ID` VARCHAR(36) NOT NULL,
    `STAFF_ID` VARCHAR(36) NOT NULL,
    `ROLE` VARCHAR(24) NOT NULL,
    `REQUESTED_MINUTES` INT UNSIGNED NOT NULL,
    `REASON` VARCHAR(1000) NOT NULL,
    `STATUS` VARCHAR(16) NOT NULL DEFAULT 'pending',
    `REQUESTED_BY` VARCHAR(36) NOT NULL,
    `REQUESTED_AT` DATETIME NOT NULL,
    `REVIEWED_BY` VARCHAR(36) NULL,
    `REVIEWED_AT` DATETIME NULL,
    `REVIEW_NOTE` VARCHAR(1000) NULL,
    PRIMARY KEY (`ID`),
    KEY `IX_SETTLEMENT_ATTENDANCE_RUN` (`SETTLEMENT_ID`, `STATUS`, `REQUESTED_AT`),
    KEY `IX_SETTLEMENT_ATTENDANCE_STAFF` (`STAFF_ID`, `REQUESTED_AT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
