-- Stage 2 additive ordering finance contract.
-- The maintenance account must never remove historical rows or schema objects.
ALTER TABLE `CUSTOMER_ORDER_SESSIONS`
    ADD COLUMN IF NOT EXISTS `ENTRY_STATUS` VARCHAR(24) NOT NULL DEFAULT 'open',
    ADD COLUMN IF NOT EXISTS `DEPARTED_AT` DATETIME(6) NULL,
    ADD COLUMN IF NOT EXISTS `DEPARTURE_REASON` VARCHAR(500) NULL;

ALTER TABLE `ORDERING_FINANCE_RECORDS`
    ADD COLUMN IF NOT EXISTS `CASE_ID` VARCHAR(36) NULL,
    ADD KEY IF NOT EXISTS `IX_ORDERING_FINANCE_RECORDS_CASE` (`CASE_ID`);

CREATE TABLE IF NOT EXISTS `ORDERING_SESSION_ADMISSIONS` (
    `ID` VARCHAR(36) NOT NULL,
    `SESSION_ID` VARCHAR(36) NOT NULL,
    `SOURCE_PERIOD_ID` VARCHAR(36) NOT NULL,
    `AMOUNT` BIGINT NOT NULL DEFAULT 0,
    `DISCOUNT_AMOUNT` BIGINT NOT NULL DEFAULT 0,
    `CREDIT_AMOUNT` BIGINT NOT NULL DEFAULT 0,
    `STATUS` VARCHAR(24) NOT NULL DEFAULT 'unpaid',
    `CASH_PERIOD_ID` VARCHAR(36) NULL,
    `CHARGE_RECORD_ID` VARCHAR(36) NULL,
    `RECEIPT_RECORD_ID` VARCHAR(36) NULL,
    `VERSION` BIGINT NOT NULL DEFAULT 0,
    `REASON` VARCHAR(500) NOT NULL,
    `CREATED_AT` DATETIME(6) NOT NULL,
    `CREATED_BY` VARCHAR(36) NOT NULL,
    `UPDATED_AT` DATETIME(6) NOT NULL,
    `UPDATED_BY` VARCHAR(36) NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UX_ORDERING_SESSION_ADMISSIONS_SESSION` (`SESSION_ID`),
    KEY `IX_ORDERING_SESSION_ADMISSIONS_PERIOD` (`SOURCE_PERIOD_ID`, `STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ORDERING_FINANCE_CASES` (
    `ID` VARCHAR(36) NOT NULL,
    `SESSION_ID` VARCHAR(36) NOT NULL,
    `RECORD_ID` VARCHAR(36) NULL,
    `ORDER_ID` VARCHAR(36) NULL,
    `ORDER_ITEM_ID` VARCHAR(36) NULL,
    `CASE_KIND` VARCHAR(32) NOT NULL,
    `AMOUNT` BIGINT NOT NULL,
    `PROFIT_SCOPE` VARCHAR(24) NOT NULL DEFAULT 'session',
    `STATUS` VARCHAR(24) NOT NULL DEFAULT 'open',
    `SOURCE_PERIOD_ID` VARCHAR(36) NOT NULL,
    `DESCRIPTION` VARCHAR(500) NOT NULL,
    `RESOLVED_AT` DATETIME(6) NULL,
    `RESOLVED_BY` VARCHAR(36) NULL,
    `RESOLUTION_NOTE` VARCHAR(500) NULL,
    `CREATED_AT` DATETIME(6) NOT NULL,
    `CREATED_BY` VARCHAR(36) NOT NULL,
    `UPDATED_AT` DATETIME(6) NOT NULL,
    `UPDATED_BY` VARCHAR(36) NOT NULL,
    PRIMARY KEY (`ID`),
    KEY `IX_ORDERING_FINANCE_CASES_SESSION` (`SESSION_ID`, `STATUS`, `CREATED_AT`),
    KEY `IX_ORDERING_FINANCE_CASES_RECORD` (`RECORD_ID`, `STATUS`),
    KEY `IX_ORDERING_FINANCE_CASES_PERIOD` (`SOURCE_PERIOD_ID`, `STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
