-- Stage 4 settlement workflow. Additive and rerunnable.
-- Historical settlement runs, finance records, and attendance events remain intact.
ALTER TABLE `SETTLEMENT_RUNS`
    ADD COLUMN IF NOT EXISTS `BUSINESS_PERIOD_ID` VARCHAR(36) NULL,
    ADD COLUMN IF NOT EXISTS `SOURCE_VERSION` BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS `SOURCE_CUTOFF_AT` DATETIME(6) NULL,
    ADD COLUMN IF NOT EXISTS `CASH_RECEIVED` DECIMAL(18,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS `CASH_REFUNDED` DECIMAL(18,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS `NET_CASH` DECIMAL(18,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS `RETAINED_AMOUNT` DECIMAL(18,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS `PENDING_FINANCE_COUNT` INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS `CORRECTS_SETTLEMENT_ID` VARCHAR(36) NULL,
    ADD COLUMN IF NOT EXISTS `CORRECTION_VERSION` INT NOT NULL DEFAULT 0,
    ADD KEY IF NOT EXISTS `IX_SETTLEMENT_RUN_PERIOD` (`BUSINESS_PERIOD_ID`);

CREATE TABLE IF NOT EXISTS `SETTLEMENT_PAYMENT_EVENTS` (
    `ID` VARCHAR(36) NOT NULL,
    `SETTLEMENT_ID` VARCHAR(36) NOT NULL,
    `STAFF_ID` VARCHAR(36) NOT NULL,
    `EVENT_KIND` VARCHAR(24) NOT NULL DEFAULT 'payout',
    `AMOUNT` BIGINT NOT NULL,
    `OPERATION_ID` VARCHAR(80) NOT NULL,
    `REASON` VARCHAR(500) NOT NULL,
    `CREATED_AT` DATETIME(6) NOT NULL,
    `CREATED_BY` VARCHAR(36) NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UX_SETTLEMENT_PAYMENT_OPERATION` (`OPERATION_ID`),
    KEY `IX_SETTLEMENT_PAYMENT_RUN_STAFF` (`SETTLEMENT_ID`, `STAFF_ID`, `CREATED_AT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `SETTLEMENT_CORRECTION_EVENTS` (
    `ID` VARCHAR(36) NOT NULL,
    `SETTLEMENT_ID` VARCHAR(36) NOT NULL,
    `CORRECTION_OF_ID` VARCHAR(36) NULL,
    `SOURCE_KIND` VARCHAR(32) NOT NULL,
    `SOURCE_ID` VARCHAR(36) NULL,
    `STAFF_ID` VARCHAR(36) NULL,
    `AMOUNT_DELTA` BIGINT NOT NULL,
    `STATUS` VARCHAR(24) NOT NULL DEFAULT 'open',
    `OPERATION_ID` VARCHAR(80) NOT NULL,
    `REASON` VARCHAR(500) NOT NULL,
    `CREATED_AT` DATETIME(6) NOT NULL,
    `CREATED_BY` VARCHAR(36) NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UX_SETTLEMENT_CORRECTION_OPERATION` (`OPERATION_ID`),
    KEY `IX_SETTLEMENT_CORRECTION_RUN_STATUS` (`SETTLEMENT_ID`, `STATUS`, `CREATED_AT`),
    KEY `IX_SETTLEMENT_CORRECTION_SOURCE` (`SOURCE_KIND`, `SOURCE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
