-- S05-a: future nomination notification schedule records.
-- This migration is intentionally not applied by the development segment.
CREATE TABLE IF NOT EXISTS `NOTIFICATION_SCHEDULES` (
    `ID` VARCHAR(40) NOT NULL,
    `SCHEDULE_KEY` VARCHAR(320) NOT NULL,
    `SOURCE_TYPE` VARCHAR(60) NOT NULL,
    `SOURCE_ID` VARCHAR(100) NOT NULL,
    `ORDER_ID` VARCHAR(40) NULL,
    `ORDER_NOMINEE_ID` VARCHAR(40) NULL,
    `OWNER_KEY` VARCHAR(90) NOT NULL,
    `RULE_ID` VARCHAR(40) NOT NULL,
    `RULE_TYPE` VARCHAR(40) NOT NULL,
    `RULE_REVISION` BIGINT NOT NULL,
    `RULE_FINGERPRINT` CHAR(64) NOT NULL,
    `OFFSET_MINUTES` SMALLINT NOT NULL,
    `SCHEDULE_REVISION` BIGINT NOT NULL DEFAULT 1,
    `DUE_AT` DATETIME(6) NOT NULL,
    `EXPIRES_AT` DATETIME(6) NOT NULL,
    `STATUS` VARCHAR(24) NOT NULL DEFAULT 'pending',
    `PROCESSED_AT` DATETIME(6) NULL,
    `INVALIDATED_AT` DATETIME(6) NULL,
    `LAST_ERROR` VARCHAR(1000) NULL,
    `CREATED_AT` DATETIME(6) NOT NULL,
    `UPDATED_AT` DATETIME(6) NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UQ_NOTIFICATION_SCHEDULE_KEY` (`SCHEDULE_KEY`),
    KEY `IX_NOTIFICATION_SCHEDULE_DUE` (`STATUS`,`DUE_AT`,`EXPIRES_AT`),
    KEY `IX_NOTIFICATION_SCHEDULE_NOMINEE` (`ORDER_NOMINEE_ID`,`STATUS`),
    KEY `IX_NOTIFICATION_SCHEDULE_OWNER` (`OWNER_KEY`,`STATUS`,`DUE_AT`),
    CONSTRAINT `FK_NOTIFICATION_SCHEDULE_ORDER`
        FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDERS` (`ID`) ON DELETE CASCADE,
    CONSTRAINT `FK_NOTIFICATION_SCHEDULE_NOMINEE`
        FOREIGN KEY (`ORDER_NOMINEE_ID`) REFERENCES `ORDER_NOMINEES` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
