-- Settlement / payroll foundation.
-- Additive only: no existing order, room, staff, or audit row is deleted or
-- overwritten. Apply this migration before deploying the settlement API.

CREATE TABLE IF NOT EXISTS `SETTLEMENT_RULE_VERSIONS` (
    `ID` VARCHAR(36) NOT NULL,
    `DAY_TYPE` VARCHAR(16) NOT NULL,
    `EFFECTIVE_FROM` DATE NOT NULL,
    `DESIGNATED_HOURLY_RATE` INT NOT NULL DEFAULT 30000,
    `SERVICE_MANAGER_HOURLY_RATE` INT NOT NULL DEFAULT 50000,
    `BACKSTAGE_HOURLY_RATE` INT NOT NULL DEFAULT 0,
    `DESIGNATED_SHARE_PERCENTAGE` DECIMAL(7,4) NOT NULL DEFAULT 70,
    `PUBLIC_ROOM_STAFF_PERCENTAGE` DECIMAL(7,4) NOT NULL DEFAULT 70,
    `DEDICATED_ROOM_OWNER_PERCENTAGE` DECIMAL(7,4) NOT NULL DEFAULT 100,
    `SERVICE_MANAGER_POOL_PERCENTAGE` DECIMAL(7,4) NOT NULL DEFAULT 25,
    `BACKSTAGE_POOL_PERCENTAGE` DECIMAL(7,4) NOT NULL DEFAULT 25,
    `COMPANY_PERCENTAGE` DECIMAL(7,4) NOT NULL DEFAULT 50,
    `TIME_ROUND_MINUTES` SMALLINT UNSIGNED NOT NULL DEFAULT 30,
    `MONEY_ROUND_UNIT` INT UNSIGNED NOT NULL DEFAULT 1,
    `PUBLIC_TIP_MODE` VARCHAR(32) NOT NULL DEFAULT 'hour_ratio',
    `CREATED_AT` DATETIME NOT NULL,
    `CREATED_BY` VARCHAR(36) NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UX_SETTLEMENT_RULE_DAY_EFFECTIVE` (`DAY_TYPE`, `EFFECTIVE_FROM`),
    KEY `IX_SETTLEMENT_RULE_EFFECTIVE` (`DAY_TYPE`, `EFFECTIVE_FROM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `SETTLEMENT_RULE_VERSIONS`
    (`ID`, `DAY_TYPE`, `EFFECTIVE_FROM`, `DESIGNATED_HOURLY_RATE`, `SERVICE_MANAGER_HOURLY_RATE`,
     `BACKSTAGE_HOURLY_RATE`, `DESIGNATED_SHARE_PERCENTAGE`, `PUBLIC_ROOM_STAFF_PERCENTAGE`,
     `DEDICATED_ROOM_OWNER_PERCENTAGE`, `SERVICE_MANAGER_POOL_PERCENTAGE`, `BACKSTAGE_POOL_PERCENTAGE`,
     `COMPANY_PERCENTAGE`, `TIME_ROUND_MINUTES`, `MONEY_ROUND_UNIT`, `PUBLIC_TIP_MODE`, `CREATED_AT`)
VALUES
    ('settlement-default-normal', 'normal', '2000-01-01', 30000, 50000, 0, 70, 70, 100, 25, 25, 50, 30, 1, 'hour_ratio', NOW()),
    ('settlement-default-event', 'event', '2000-01-01', 30000, 50000, 0, 70, 70, 100, 25, 25, 50, 30, 1, 'hour_ratio', NOW())
ON DUPLICATE KEY UPDATE `ID` = VALUES(`ID`);

CREATE TABLE IF NOT EXISTS `SETTLEMENT_RUNS` (
    `ID` VARCHAR(36) NOT NULL,
    `BUSINESS_DATE` DATE NOT NULL,
    `SESSION_NO` INT UNSIGNED NOT NULL DEFAULT 1,
    `DAY_TYPE` VARCHAR(16) NOT NULL DEFAULT 'normal',
    `STATUS` VARCHAR(24) NOT NULL DEFAULT 'draft',
    `RULE_VERSION_ID` VARCHAR(36) NULL,
    `RULE_SNAPSHOT_JSON` LONGTEXT NULL,
    `PUBLIC_TIP_AMOUNT` INT NOT NULL DEFAULT 0,
    `ADMISSION_FEE_OVERRIDE` INT NULL,
    `ADMISSION_FEE_SNAPSHOT` INT NOT NULL DEFAULT 0,
    `ACTIVITY_EXPENSE` INT NOT NULL DEFAULT 0,
    `COMPANY_SHARE_HOURS` DECIMAL(10,2) NULL,
    `ACTIVITY_HOURS_CONFIRMED` TINYINT(1) NOT NULL DEFAULT 0,
    `GROSS_REVENUE` DECIMAL(18,2) NOT NULL DEFAULT 0,
    `DESIGNATED_REVENUE_BASE` DECIMAL(18,2) NOT NULL DEFAULT 0,
    `DEDICATED_ROOM_GROSS` DECIMAL(18,2) NOT NULL DEFAULT 0,
    `DEDICATED_ROOM_OWNER_SHARE` DECIMAL(18,2) NOT NULL DEFAULT 0,
    `DEDICATED_ROOM_COMPANY_REMAINDER` DECIMAL(18,2) NOT NULL DEFAULT 0,
    `PUBLIC_ROOM_UNASSIGNED_REVENUE` DECIMAL(18,2) NOT NULL DEFAULT 0,
    `ADMISSION_REVENUE` DECIMAL(18,2) NOT NULL DEFAULT 0,
    `MEAL_REVENUE` DECIMAL(18,2) NOT NULL DEFAULT 0,
    `COMPANY_REVENUE` DECIMAL(18,2) NOT NULL DEFAULT 0,
    `SERVICE_MANAGER_POOL` DECIMAL(18,2) NOT NULL DEFAULT 0,
    `BACKSTAGE_POOL` DECIMAL(18,2) NOT NULL DEFAULT 0,
    `COMPANY_INCOME` DECIMAL(18,2) NOT NULL DEFAULT 0,
    `ACTIVITY_NET_REVENUE` DECIMAL(18,2) NOT NULL DEFAULT 0,
    `FINALIZED_AT` DATETIME NULL,
    `FINALIZED_BY` VARCHAR(36) NULL,
    `CREATED_AT` DATETIME NOT NULL,
    `CREATED_BY` VARCHAR(36) NULL,
    `UPDATED_AT` DATETIME NOT NULL,
    `UPDATED_BY` VARCHAR(36) NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UX_SETTLEMENT_RUN_DATE_SESSION` (`BUSINESS_DATE`, `SESSION_NO`),
    KEY `IX_SETTLEMENT_RUN_STATUS` (`BUSINESS_DATE`, `STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `SETTLEMENT_STAFF_INPUTS` (
    `ID` VARCHAR(36) NOT NULL,
    `SETTLEMENT_ID` VARCHAR(36) NOT NULL,
    `STAFF_ID` VARCHAR(36) NOT NULL,
    `ROLE` VARCHAR(24) NOT NULL,
    `ACTUAL_MINUTES` INT UNSIGNED NOT NULL DEFAULT 0,
    `ACTIVITY_HOURS` DECIMAL(10,2) NULL,
    `PUBLIC_TIP_ELIGIBLE` TINYINT(1) NOT NULL DEFAULT 1,
    `IS_BACKSTAGE_PARTICIPANT` TINYINT(1) NOT NULL DEFAULT 0,
    `NOTE` VARCHAR(500) NULL,
    `CREATED_AT` DATETIME NOT NULL,
    `CREATED_BY` VARCHAR(36) NULL,
    `UPDATED_AT` DATETIME NOT NULL,
    `UPDATED_BY` VARCHAR(36) NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UX_SETTLEMENT_INPUT_STAFF_ROLE` (`SETTLEMENT_ID`, `STAFF_ID`, `ROLE`),
    KEY `IX_SETTLEMENT_INPUT_RUN_ROLE` (`SETTLEMENT_ID`, `ROLE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `SETTLEMENT_ORDER_ADJUSTMENTS` (
    `ID` VARCHAR(36) NOT NULL,
    `SETTLEMENT_ID` VARCHAR(36) NOT NULL,
    `SOURCE_TYPE` VARCHAR(24) NOT NULL DEFAULT 'order',
    `SOURCE_ID` VARCHAR(36) NOT NULL,
    `ORIGINAL_AMOUNT` INT NOT NULL,
    `ADJUSTED_AMOUNT` INT NOT NULL,
    `REASON` VARCHAR(1000) NOT NULL,
    `NOTE` VARCHAR(1000) NULL,
    `CREATED_AT` DATETIME NOT NULL,
    `CREATED_BY` VARCHAR(36) NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UX_SETTLEMENT_ADJUSTMENT_SOURCE` (`SETTLEMENT_ID`, `SOURCE_TYPE`, `SOURCE_ID`),
    KEY `IX_SETTLEMENT_ADJUSTMENT_RUN` (`SETTLEMENT_ID`, `CREATED_AT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `SETTLEMENT_RESULT_LINES` (
    `ID` VARCHAR(36) NOT NULL,
    `SETTLEMENT_ID` VARCHAR(36) NOT NULL,
    `STAFF_ID` VARCHAR(36) NULL,
    `ROLE` VARCHAR(32) NOT NULL,
    `PAYABLE_HOURS` DECIMAL(10,2) NOT NULL DEFAULT 0,
    `HOURLY_RATE` INT NOT NULL DEFAULT 0,
    `BASE_PAY` DECIMAL(18,2) NOT NULL DEFAULT 0,
    `REVENUE_BASE` DECIMAL(18,2) NOT NULL DEFAULT 0,
    `REVENUE_PERCENTAGE` DECIMAL(7,4) NOT NULL DEFAULT 0,
    `REVENUE_SHARE` DECIMAL(18,2) NOT NULL DEFAULT 0,
    `DESIGNATED_TIP` DECIMAL(18,2) NOT NULL DEFAULT 0,
    `PUBLIC_TIP` DECIMAL(18,2) NOT NULL DEFAULT 0,
    `PREFERRED_PAY` DECIMAL(18,2) NOT NULL DEFAULT 0,
    `BEFORE_ROUNDING` DECIMAL(18,2) NOT NULL DEFAULT 0,
    `AFTER_ROUNDING` INT NOT NULL DEFAULT 0,
    `COMPANY_SUBSIDY` DECIMAL(18,2) NOT NULL DEFAULT 0,
    `MANUAL_ADJUSTMENT` DECIMAL(18,2) NOT NULL DEFAULT 0,
    `ANOMALY_STATUS` VARCHAR(24) NOT NULL DEFAULT 'normal',
    `ANOMALY_NOTE` VARCHAR(1000) NULL,
    `CREATED_AT` DATETIME NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UX_SETTLEMENT_RESULT_STAFF_ROLE` (`SETTLEMENT_ID`, `STAFF_ID`, `ROLE`),
    KEY `IX_SETTLEMENT_RESULT_RUN` (`SETTLEMENT_ID`, `ROLE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `SETTLEMENT_AUDIT_LOG` (
    `ID` VARCHAR(36) NOT NULL,
    `SETTLEMENT_ID` VARCHAR(36) NULL,
    `ACTION_TYPE` VARCHAR(64) NOT NULL,
    `BEFORE_JSON` LONGTEXT NULL,
    `AFTER_JSON` LONGTEXT NULL,
    `REASON` VARCHAR(1000) NULL,
    `ACTOR_ID` VARCHAR(36) NULL,
    `CREATED_AT` DATETIME NOT NULL,
    PRIMARY KEY (`ID`),
    KEY `IX_SETTLEMENT_AUDIT_RUN` (`SETTLEMENT_ID`, `CREATED_AT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
