-- S1. Preserve original booking snapshots and record late starts, conflicts and compensation.
ALTER TABLE `ORDER_FULFILLMENT_UNITS`
  ADD COLUMN IF NOT EXISTS `ORIGINAL_SCHEDULED_STARTS_AT` DATETIME(6) NULL AFTER `SCHEDULED_STARTS_AT`,
  ADD COLUMN IF NOT EXISTS `ORIGINAL_SCHEDULED_ENDS_AT` DATETIME(6) NULL AFTER `SCHEDULED_ENDS_AT`,
  ADD COLUMN IF NOT EXISTS `REST_MINUTES_RESERVED` INT NOT NULL DEFAULT 0 AFTER `PURCHASED_MINUTES`,
  ADD COLUMN IF NOT EXISTS `FULFILLMENT_PERIOD_ID` CHAR(36) NULL AFTER `BUSINESS_PERIOD_ID`;

UPDATE `ORDER_FULFILLMENT_UNITS`
SET `ORIGINAL_SCHEDULED_STARTS_AT`=COALESCE(`ORIGINAL_SCHEDULED_STARTS_AT`,`SCHEDULED_STARTS_AT`),
    `ORIGINAL_SCHEDULED_ENDS_AT`=COALESCE(`ORIGINAL_SCHEDULED_ENDS_AT`,`SCHEDULED_ENDS_AT`),
    `REST_MINUTES_RESERVED`=CASE WHEN `REST_MINUTES_RESERVED`=0 AND `KIND`='nominee' THEN 10 ELSE `REST_MINUTES_RESERVED` END,
    `FULFILLMENT_PERIOD_ID`=COALESCE(`FULFILLMENT_PERIOD_ID`,`BUSINESS_PERIOD_ID`)
WHERE `ORIGINAL_SCHEDULED_STARTS_AT` IS NULL OR `ORIGINAL_SCHEDULED_ENDS_AT` IS NULL OR `FULFILLMENT_PERIOD_ID` IS NULL;

CREATE INDEX IF NOT EXISTS `IX_FULFILLMENT_ACTIVE_PERIOD`
  ON `ORDER_FULFILLMENT_UNITS` (`FULFILLMENT_PERIOD_ID`,`UNIT_STATUS`,`SCHEDULED_STARTS_AT`);

CREATE TABLE IF NOT EXISTS `ORDER_FULFILLMENT_EVENTS` (
  `ID` CHAR(36) NOT NULL PRIMARY KEY,
  `ORDER_ID` CHAR(36) NOT NULL,
  `UNIT_ID` CHAR(36) NOT NULL,
  `EVENT_TYPE` VARCHAR(32) NOT NULL,
  `OPERATION_ID` CHAR(36) NOT NULL,
  `FROM_PERIOD_ID` CHAR(36) NULL,
  `TO_PERIOD_ID` CHAR(36) NULL,
  `ORIGINAL_STARTS_AT` DATETIME(6) NULL,
  `ORIGINAL_ENDS_AT` DATETIME(6) NULL,
  `EFFECTIVE_STARTS_AT` DATETIME(6) NULL,
  `EFFECTIVE_ENDS_AT` DATETIME(6) NULL,
  `ACTUAL_STARTS_AT` DATETIME(6) NULL,
  `ACTUAL_ENDS_AT` DATETIME(6) NULL,
  `REST_MINUTES` INT NULL,
  `COMPENSATION_AMOUNT` BIGINT NOT NULL DEFAULT 0,
  `REASON` VARCHAR(500) NULL,
  `ACTOR_ID` CHAR(36) NOT NULL,
  `CREATED_AT` DATETIME(6) NOT NULL,
  UNIQUE KEY `UK_FULFILLMENT_EVENT_OPERATION` (`OPERATION_ID`,`EVENT_TYPE`),
  KEY `IX_FULFILLMENT_EVENTS_UNIT` (`UNIT_ID`,`CREATED_AT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ORDER_FULFILLMENT_CONFLICTS` (
  `ID` CHAR(36) NOT NULL PRIMARY KEY,
  `CURRENT_UNIT_ID` CHAR(36) NOT NULL,
  `AFFECTED_UNIT_ID` CHAR(36) NOT NULL,
  `STAFF_ID` CHAR(36) NOT NULL,
  `OVERLAP_MINUTES` INT NOT NULL,
  `STATUS` VARCHAR(24) NOT NULL DEFAULT 'needs_coordination',
  `REASON` VARCHAR(500) NULL,
  `RESOLVED_AT` DATETIME(6) NULL,
  `RESOLVED_BY` CHAR(36) NULL,
  `CREATED_AT` DATETIME(6) NOT NULL,
  KEY `IX_FULFILLMENT_CONFLICT_STAFF` (`STAFF_ID`,`STATUS`),
  KEY `IX_FULFILLMENT_CONFLICT_UNIT` (`AFFECTED_UNIT_ID`,`STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
