-- Business-day windows and immutable nomination duration snapshots.
-- Apply this migration before deploying the matching API build.
-- A 00:00 start with next-day 00:00 end preserves the previous 24-hour behaviour.

ALTER TABLE `ORDERING_SETTINGS`
    ADD COLUMN IF NOT EXISTS `BUSINESS_DAY_START_MINUTE` SMALLINT UNSIGNED NOT NULL DEFAULT 0 AFTER `EXPIRE_AFTER_MINUTES`,
    ADD COLUMN IF NOT EXISTS `BUSINESS_DAY_END_MINUTE` SMALLINT UNSIGNED NOT NULL DEFAULT 0 AFTER `BUSINESS_DAY_START_MINUTE`,
    ADD COLUMN IF NOT EXISTS `BUSINESS_DAY_ENDS_NEXT_DAY` TINYINT(1) NOT NULL DEFAULT 1 AFTER `BUSINESS_DAY_END_MINUTE`;

CREATE TABLE IF NOT EXISTS `BUSINESS_PERIODS` (
    `ID` VARCHAR(36) NOT NULL,
    `BUSINESS_DATE` DATE NOT NULL,
    `STARTS_AT` DATETIME NOT NULL,
    `ENDS_AT` DATETIME NOT NULL,
    `TIMEZONE` VARCHAR(64) NOT NULL DEFAULT 'Asia/Taipei',
    `PERIOD_STATUS` VARCHAR(24) NOT NULL DEFAULT 'open',
    `CREATED_AT` DATETIME NOT NULL,
    `UPDATED_AT` DATETIME NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UX_BUSINESS_PERIODS_DATE` (`BUSINESS_DATE`),
    KEY `IX_BUSINESS_PERIODS_ACTIVE` (`PERIOD_STATUS`, `STARTS_AT`, `ENDS_AT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `ORDER_NOMINEES`
    ADD COLUMN IF NOT EXISTS `SEGMENT_MINUTES_SNAPSHOT` INT NOT NULL DEFAULT 20 AFTER `SERVICE_DURATION_MINUTES`,
    ADD COLUMN IF NOT EXISTS `RESERVED_MINUTES` INT NOT NULL DEFAULT 20 AFTER `SEGMENT_MINUTES_SNAPSHOT`,
    ADD COLUMN IF NOT EXISTS `BUFFER_MINUTES_SNAPSHOT` INT NOT NULL DEFAULT 0 AFTER `RESERVED_MINUTES`;

ALTER TABLE `ORDER_NOMINEES`
    MODIFY COLUMN `SERVICE_ID` VARCHAR(36) NULL,
    ADD COLUMN IF NOT EXISTS `NOMINATION_MODE` VARCHAR(24) NOT NULL DEFAULT 'service' AFTER `SERVICE_NAME_SNAPSHOT`;

ALTER TABLE `ORDERS`
    ADD COLUMN IF NOT EXISTS `ORDER_KIND` VARCHAR(24) NOT NULL DEFAULT 'standard' AFTER `ORDER_NUMBER`,
    ADD COLUMN IF NOT EXISTS `PARENT_NOMINEE_ID` VARCHAR(36) NULL AFTER `ORDER_KIND`,
    ADD KEY IF NOT EXISTS `IX_ORDERS_PARENT_NOMINEE` (`PARENT_NOMINEE_ID`, `SUBMITTED_AT`);

CREATE TABLE IF NOT EXISTS `ORDER_SERVICE_ADDONS` (
    `ID` VARCHAR(36) NOT NULL,
    `ORDER_ID` VARCHAR(36) NOT NULL,
    `PARENT_NOMINEE_ID` VARCHAR(36) NOT NULL,
    `STAFF_ID` VARCHAR(36) NOT NULL,
    `STAFF_NAME_SNAPSHOT` VARCHAR(100) NOT NULL,
    `SERVICE_ID` VARCHAR(36) NOT NULL,
    `SERVICE_NAME_SNAPSHOT` VARCHAR(160) NOT NULL,
    `SEGMENT_COUNT` INT NOT NULL DEFAULT 1,
    `SERVICE_DURATION_MINUTES` INT NOT NULL,
    `PARTICIPANT_COUNT` INT NOT NULL DEFAULT 1,
    `ADDON_STATUS` VARCHAR(24) NOT NULL DEFAULT 'waiting',
    `CONFIRMED_AT` DATETIME NULL,
    `CONFIRMED_BY` VARCHAR(36) NULL,
    `CREATED_AT` DATETIME NOT NULL,
    `UPDATED_AT` DATETIME NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UX_ORDER_SERVICE_ADDONS_ORDER` (`ORDER_ID`),
    KEY `IX_ORDER_SERVICE_ADDONS_PARENT` (`PARENT_NOMINEE_ID`, `CREATED_AT`),
    KEY `IX_ORDER_SERVICE_ADDONS_STAFF` (`STAFF_ID`, `ADDON_STATUS`, `CREATED_AT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

UPDATE `ORDER_NOMINEES`
SET `RESERVED_MINUTES` = GREATEST(1, TIMESTAMPDIFF(MINUTE, `REQUESTED_STARTS_AT`, `REQUESTED_SERVICE_ENDS_AT`)),
    `BUFFER_MINUTES_SNAPSHOT` = GREATEST(0, TIMESTAMPDIFF(MINUTE, `REQUESTED_SERVICE_ENDS_AT`, `REQUESTED_BUSY_UNTIL`)),
    `SEGMENT_MINUTES_SNAPSHOT` = GREATEST(1,
        CEIL(TIMESTAMPDIFF(MINUTE, `REQUESTED_STARTS_AT`, `REQUESTED_SERVICE_ENDS_AT`) / `SEGMENT_COUNT`));
