CREATE TABLE IF NOT EXISTS NOTIFICATION_SOUNDS (
  ID VARCHAR(40) NOT NULL PRIMARY KEY,
  OWNER_STAFF_ID VARCHAR(40) NULL,
  SYSTEM_CODE VARCHAR(60) NULL,
  NAME VARCHAR(80) NOT NULL,
  FILE_NAME VARCHAR(100) NOT NULL,
  MIME_TYPE VARCHAR(40) NOT NULL,
  DURATION_MS INT NOT NULL,
  CREATED_AT DATETIME(6) NOT NULL,
  UNIQUE KEY UQ_NOTIFICATION_SYSTEM_SOUND (SYSTEM_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
