-- Operational business-period state machine.
-- Scheduled hours remain defaults and reminders; actual open/close actions control ordering.
-- This migration is additive and uses no DELETE or DROP statements.

ALTER TABLE `BUSINESS_PERIODS`
    ADD COLUMN IF NOT EXISTS `ACTUAL_OPENED_AT` DATETIME NULL AFTER `ENDS_AT`,
    ADD COLUMN IF NOT EXISTS `PROJECTED_CLOSE_AT` DATETIME NULL AFTER `ACTUAL_OPENED_AT`,
    ADD COLUMN IF NOT EXISTS `ACTUAL_CLOSED_AT` DATETIME NULL AFTER `PROJECTED_CLOSE_AT`,
    ADD COLUMN IF NOT EXISTS `SETTLED_AT` DATETIME NULL AFTER `ACTUAL_CLOSED_AT`,
    ADD COLUMN IF NOT EXISTS `INTAKE_MODE` VARCHAR(24) NOT NULL DEFAULT 'normal' AFTER `PERIOD_STATUS`,
    ADD COLUMN IF NOT EXISTS `UPDATED_BY` VARCHAR(36) NULL AFTER `UPDATED_AT`;

UPDATE `BUSINESS_PERIODS`
SET `ACTUAL_OPENED_AT` = COALESCE(`ACTUAL_OPENED_AT`, `STARTS_AT`),
    `PROJECTED_CLOSE_AT` = COALESCE(`PROJECTED_CLOSE_AT`, `ENDS_AT`),
    `INTAKE_MODE` = CASE
        WHEN `PERIOD_STATUS` = 'open' THEN COALESCE(NULLIF(`INTAKE_MODE`, ''), 'normal')
        ELSE 'staff_only'
    END
WHERE `ACTUAL_OPENED_AT` IS NULL
   OR `PROJECTED_CLOSE_AT` IS NULL
   OR `INTAKE_MODE` IS NULL
   OR `INTAKE_MODE` = '';

-- Legacy periods were schedule snapshots and were never explicitly closed. Mark only
-- periods whose original scheduled end is already past as settled, so they cannot
-- become the active operational period after this release. A currently running
-- legacy period remains open as a safe in-place transition.
UPDATE `BUSINESS_PERIODS`
SET `PERIOD_STATUS` = 'settled',
    `INTAKE_MODE` = 'staff_only',
    `ACTUAL_CLOSED_AT` = COALESCE(`ACTUAL_CLOSED_AT`, `ENDS_AT`),
    `SETTLED_AT` = COALESCE(`SETTLED_AT`, `ENDS_AT`),
    `UPDATED_AT` = NOW(),
    `UPDATED_BY` = 'migration:20260831_02'
WHERE `PERIOD_STATUS` IN ('open', 'closed')
  AND `ENDS_AT` <= NOW()
  AND `SETTLED_AT` IS NULL;

ALTER TABLE `BUSINESS_PERIODS`
    ADD KEY IF NOT EXISTS `IX_BUSINESS_PERIODS_OPERATIONAL` (`PERIOD_STATUS`, `ACTUAL_OPENED_AT`, `SETTLED_AT`),
    ADD KEY IF NOT EXISTS `IX_BUSINESS_PERIODS_PROJECTED_CLOSE` (`PERIOD_STATUS`, `INTAKE_MODE`, `PROJECTED_CLOSE_AT`);

ALTER TABLE `ORDERS`
    ADD COLUMN IF NOT EXISTS `INTAKE_MODE_SNAPSHOT` VARCHAR(24) NOT NULL DEFAULT 'normal' AFTER `ORDER_STATUS`,
    ADD COLUMN IF NOT EXISTS `STORE_CONFIRMATION_STATUS` VARCHAR(24) NOT NULL DEFAULT 'not_required' AFTER `INTAKE_MODE_SNAPSHOT`,
    ADD COLUMN IF NOT EXISTS `STORE_CONFIRMED_AT` DATETIME NULL AFTER `STORE_CONFIRMATION_STATUS`,
    ADD COLUMN IF NOT EXISTS `STORE_CONFIRMED_BY` VARCHAR(36) NULL AFTER `STORE_CONFIRMED_AT`,
    ADD KEY IF NOT EXISTS `IX_ORDERS_STORE_CONFIRMATION` (`STORE_CONFIRMATION_STATUS`, `QUEUE_ENTERED_AT`);

UPDATE `ORDERS`
SET `INTAKE_MODE_SNAPSHOT` = COALESCE(NULLIF(`INTAKE_MODE_SNAPSHOT`, ''), 'normal'),
    `STORE_CONFIRMATION_STATUS` = COALESCE(NULLIF(`STORE_CONFIRMATION_STATUS`, ''), 'not_required')
WHERE `INTAKE_MODE_SNAPSHOT` IS NULL
   OR `INTAKE_MODE_SNAPSHOT` = ''
   OR `STORE_CONFIRMATION_STATUS` IS NULL
   OR `STORE_CONFIRMATION_STATUS` = '';
