-- Apply after 20260921_01_customer_commissions.sql and the existing guestbook migration.
-- Additive and repeatable on the project's MariaDB dialect. No credential plaintext is stored.
ALTER TABLE GUESTBOOK_COMMENTS
  ADD COLUMN IF NOT EXISTS CUSTOMER_UID VARCHAR(32) NULL,
  ADD COLUMN IF NOT EXISTS IMAGE_ID CHAR(36) NULL;
ALTER TABLE GUESTBOOK_REPLIES
  ADD COLUMN IF NOT EXISTS CUSTOMER_UID VARCHAR(32) NULL,
  ADD COLUMN IF NOT EXISTS IMAGE_ID CHAR(36) NULL;
CREATE TABLE IF NOT EXISTS GUESTBOOK_IMAGES (
  ID CHAR(36) NOT NULL PRIMARY KEY,
  IMAGE_BYTES MEDIUMBLOB NOT NULL,
  CREATED_AT DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE INDEX IF NOT EXISTS IX_GUESTBOOK_COMMENT_IMAGE ON GUESTBOOK_COMMENTS (IMAGE_ID);
CREATE INDEX IF NOT EXISTS IX_GUESTBOOK_REPLY_IMAGE ON GUESTBOOK_REPLIES (IMAGE_ID);
CREATE INDEX IF NOT EXISTS IX_GUESTBOOK_COMMENT_CUSTOMER ON GUESTBOOK_COMMENTS (CUSTOMER_UID, CREATED_AT);
CREATE INDEX IF NOT EXISTS IX_GUESTBOOK_REPLY_CUSTOMER ON GUESTBOOK_REPLIES (CUSTOMER_UID, CREATED_AT);
