-- Room service foundation: public room catalogue, staff-only service orders,
-- and payroll sharing settings. This migration intentionally uses only
-- additive DDL; apply it with a DBA / deployment identity that owns schema changes.

CREATE TABLE IF NOT EXISTS `ROOMS` (
    `ID` VARCHAR(36) NOT NULL,
    `ROOM_NAME` VARCHAR(100) NOT NULL,
    `SHORT_DESCRIPTION` VARCHAR(500) NOT NULL,
    `DETAIL_CONTENT` TEXT NULL,
    `OWNER_STAFF_ID` VARCHAR(36) NULL,
    `SEGMENT_PRICE` INT NOT NULL DEFAULT 0,
    `IS_ACTIVE` BOOLEAN NOT NULL DEFAULT TRUE,
    `SORT_ORDER` INT NOT NULL DEFAULT 0,
    `CREATED_AT` DATETIME NOT NULL,
    `CREATED_BY` VARCHAR(36) NULL,
    `UPDATED_AT` DATETIME NOT NULL,
    `UPDATED_BY` VARCHAR(36) NULL,
    PRIMARY KEY (`ID`),
    KEY `IX_ROOMS_ACTIVE_ORDER` (`IS_ACTIVE`, `SORT_ORDER`, `ROOM_NAME`),
    KEY `IX_ROOMS_OWNER` (`OWNER_STAFF_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ROOM_PHOTO_ITEMS` (
    `ID` VARCHAR(36) NOT NULL,
    `ROOM_ID` VARCHAR(36) NOT NULL,
    `MEDIA_ID` VARCHAR(36) NOT NULL,
    `SORT_ORDER` INT NOT NULL DEFAULT 0,
    `CREATED_AT` DATETIME NOT NULL,
    `CREATED_BY` VARCHAR(36) NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UX_ROOM_PHOTO_ITEMS_ROOM_MEDIA` (`ROOM_ID`, `MEDIA_ID`),
    KEY `IX_ROOM_PHOTO_ITEMS_ROOM` (`ROOM_ID`, `SORT_ORDER`),
    KEY `IX_ROOM_PHOTO_ITEMS_MEDIA` (`MEDIA_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ROOM_SERVICE_ORDERS` (
    `ID` VARCHAR(36) NOT NULL,
    `ROOM_ID` VARCHAR(36) NOT NULL,
    `ROOM_NAME_SNAPSHOT` VARCHAR(100) NOT NULL,
    `BUSINESS_DATE` DATE NOT NULL,
    `STARTS_AT` DATETIME NOT NULL,
    `ENDS_AT` DATETIME NOT NULL,
    `SEGMENT_COUNT` INT NOT NULL,
    `SEGMENT_MINUTES_SNAPSHOT` INT NOT NULL,
    `UNIT_PRICE` INT NOT NULL,
    `TOTAL_AMOUNT` INT NOT NULL,
    `ORDER_STATUS` VARCHAR(24) NOT NULL DEFAULT 'scheduled',
    `NOTE` VARCHAR(500) NULL,
    `CREATED_AT` DATETIME NOT NULL,
    `CREATED_BY` VARCHAR(36) NULL,
    `UPDATED_AT` DATETIME NOT NULL,
    `UPDATED_BY` VARCHAR(36) NULL,
    PRIMARY KEY (`ID`),
    KEY `IX_ROOM_SERVICE_ORDERS_DATE` (`BUSINESS_DATE`, `STARTS_AT`),
    KEY `IX_ROOM_SERVICE_ORDERS_ROOM_STATUS` (`ROOM_ID`, `ORDER_STATUS`, `STARTS_AT`, `ENDS_AT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ROOM_PROFIT_SHARING_SETTINGS` (
    `ID` VARCHAR(36) NOT NULL,
    `COMMON_ROOM_STAFF_PERCENTAGE` INT NOT NULL DEFAULT 0,
    `DEDICATED_ROOM_STAFF_PERCENTAGE` INT NOT NULL DEFAULT 100,
    `UPDATED_AT` DATETIME NOT NULL,
    `UPDATED_BY` VARCHAR(36) NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `ROOM_PROFIT_SHARING_SETTINGS`
    (`ID`, `COMMON_ROOM_STAFF_PERCENTAGE`, `DEDICATED_ROOM_STAFF_PERCENTAGE`, `UPDATED_AT`)
VALUES ('default', 0, 100, NOW())
ON DUPLICATE KEY UPDATE `ID` = VALUES(`ID`);
