-- Stage 0: additive, rerunnable on MariaDB 11. Existing business days stay on flow 1.
ALTER TABLE BUSINESS_PERIODS ADD COLUMN IF NOT EXISTS FLOW_VERSION INT NOT NULL DEFAULT 1;
ALTER TABLE BUSINESS_PERIODS ADD COLUMN IF NOT EXISTS VERSION INT NOT NULL DEFAULT 1;
ALTER TABLE CUSTOMER_ORDER_SESSIONS ADD COLUMN IF NOT EXISTS BUSINESS_PERIOD_ID CHAR(36) NULL;
ALTER TABLE ORDERS ADD COLUMN IF NOT EXISTS BUSINESS_PERIOD_ID CHAR(36) NULL;
ALTER TABLE ORDERS ADD COLUMN IF NOT EXISTS FLOW_VERSION INT NOT NULL DEFAULT 1;
ALTER TABLE STAFF_DAILY_WORK_MODES ADD COLUMN IF NOT EXISTS STOP_ACCEPTING_NEW_ORDERS BOOLEAN NOT NULL DEFAULT FALSE;
CREATE INDEX IF NOT EXISTS IX_SESSION_BUSINESS_PERIOD ON CUSTOMER_ORDER_SESSIONS(BUSINESS_PERIOD_ID);
CREATE INDEX IF NOT EXISTS IX_ORDER_BUSINESS_PERIOD ON ORDERS(BUSINESS_PERIOD_ID);
UPDATE CUSTOMER_ORDER_SESSIONS S JOIN BUSINESS_PERIODS P ON P.BUSINESS_DATE=S.BUSINESS_DATE
SET S.BUSINESS_PERIOD_ID=P.ID WHERE S.BUSINESS_PERIOD_ID IS NULL;
UPDATE ORDERS O JOIN CUSTOMER_ORDER_SESSIONS S ON S.ID=O.SESSION_ID
SET O.BUSINESS_PERIOD_ID=S.BUSINESS_PERIOD_ID WHERE O.BUSINESS_PERIOD_ID IS NULL;
CREATE TABLE IF NOT EXISTS BUSINESS_DAY_PLANS (
 BUSINESS_DATE DATE NOT NULL PRIMARY KEY, STARTS_AT DATETIME(6) NOT NULL, ENDS_AT DATETIME(6) NOT NULL,
 VERSION INT NOT NULL DEFAULT 1, UPDATED_BY VARCHAR(100) NOT NULL, UPDATED_AT DATETIME(6) NOT NULL,
 REASON VARCHAR(500) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS ORDERING_RUNTIME_LOCKS (ID VARCHAR(64) PRIMARY KEY) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT IGNORE INTO ORDERING_RUNTIME_LOCKS(ID) VALUES ('operating_period');
CREATE TABLE IF NOT EXISTS BUSINESS_PERIOD_OPERATIONS (
 OPERATION_ID VARCHAR(80) PRIMARY KEY, PAYLOAD_HASH CHAR(64) NOT NULL, BUSINESS_DATE DATE NOT NULL,
 PERIOD_ID CHAR(36) NULL, ACTION VARCHAR(40) NOT NULL, ACTOR_ID VARCHAR(100) NOT NULL,
 CREATED_AT DATETIME(6) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
