-- Configurable customer tip presets. This migration only adds columns and
-- updates the singleton settings row; it does not delete tables or data.

ALTER TABLE `ORDERING_SETTINGS`
    ADD COLUMN IF NOT EXISTS `TIP_PRESET_AMOUNT_1` INT UNSIGNED NOT NULL DEFAULT 50 AFTER `BASE_NOMINATION_FEE`,
    ADD COLUMN IF NOT EXISTS `TIP_PRESET_AMOUNT_2` INT UNSIGNED NOT NULL DEFAULT 100 AFTER `TIP_PRESET_AMOUNT_1`,
    ADD COLUMN IF NOT EXISTS `TIP_PRESET_AMOUNT_3` INT UNSIGNED NOT NULL DEFAULT 200 AFTER `TIP_PRESET_AMOUNT_2`,
    ADD COLUMN IF NOT EXISTS `TIP_PRESET_AMOUNT_4` INT UNSIGNED NOT NULL DEFAULT 500 AFTER `TIP_PRESET_AMOUNT_3`;

UPDATE `ORDERING_SETTINGS`
SET `TIP_PRESET_AMOUNT_1` = CASE WHEN `TIP_PRESET_AMOUNT_1` = 0 THEN 50 ELSE `TIP_PRESET_AMOUNT_1` END,
    `TIP_PRESET_AMOUNT_2` = CASE WHEN `TIP_PRESET_AMOUNT_2` = 0 THEN 100 ELSE `TIP_PRESET_AMOUNT_2` END,
    `TIP_PRESET_AMOUNT_3` = CASE WHEN `TIP_PRESET_AMOUNT_3` = 0 THEN 200 ELSE `TIP_PRESET_AMOUNT_3` END,
    `TIP_PRESET_AMOUNT_4` = CASE WHEN `TIP_PRESET_AMOUNT_4` = 0 THEN 500 ELSE `TIP_PRESET_AMOUNT_4` END
WHERE `ID` = 'default';
