-- S13: notification sound soft-delete, version and content hash metadata.
-- Apply after 20260909_08_notification_changes.sql.
ALTER TABLE `NOTIFICATION_SOUNDS`
    ADD COLUMN IF NOT EXISTS `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1 AFTER `DURATION_MS`;

ALTER TABLE `NOTIFICATION_SOUNDS`
    ADD COLUMN IF NOT EXISTS `VERSION` INT NOT NULL DEFAULT 1 AFTER `IS_ACTIVE`;

ALTER TABLE `NOTIFICATION_SOUNDS`
    ADD COLUMN IF NOT EXISTS `SHA256_HASH` CHAR(64) NULL AFTER `VERSION`;

ALTER TABLE `NOTIFICATION_SOUNDS`
    ADD COLUMN IF NOT EXISTS `UPDATED_AT` DATETIME(6) NULL AFTER `CREATED_AT`;

ALTER TABLE `NOTIFICATION_SOUNDS`
    ADD COLUMN IF NOT EXISTS `DELETED_AT` DATETIME(6) NULL AFTER `UPDATED_AT`;

UPDATE `NOTIFICATION_SOUNDS`
SET `UPDATED_AT`=COALESCE(`UPDATED_AT`,`CREATED_AT`),
    `IS_ACTIVE`=COALESCE(`IS_ACTIVE`,1),
    `VERSION`=COALESCE(`VERSION`,1)
WHERE `UPDATED_AT` IS NULL OR `IS_ACTIVE` IS NULL OR `VERSION` IS NULL;

ALTER TABLE `NOTIFICATION_SOUNDS`
    ADD KEY IF NOT EXISTS `IX_NOTIFICATION_SOUND_ACTIVE`
        (`IS_ACTIVE`,`SYSTEM_CODE`,`OWNER_STAFF_ID`);
