-- Stage 0 additive finance contract. Apply after 20260914_01.
-- Existing order amounts are receivables, never evidence of historical cash.
-- Re-runnable; no historical cash events or salary settlements are generated.
CREATE TABLE IF NOT EXISTS `ORDERING_FINANCE_ACCOUNTS` (
    `SESSION_ID` VARCHAR(36) NOT NULL,
    `SOURCE_PERIOD_ID` VARCHAR(36) NOT NULL,
    `VERSION` BIGINT NOT NULL DEFAULT 0,
    `UPDATED_AT` DATETIME(6) NOT NULL,
    PRIMARY KEY (`SESSION_ID`),
    KEY `IX_ORDERING_FINANCE_ACCOUNTS_PERIOD` (`SOURCE_PERIOD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ORDERING_FINANCE_RECORDS` (
    `ID` VARCHAR(36) NOT NULL,
    `SESSION_ID` VARCHAR(36) NOT NULL,
    `VERSION` BIGINT NOT NULL,
    `KIND` VARCHAR(24) NOT NULL,
    `AMOUNT` BIGINT NOT NULL,
    `SOURCE_KIND` VARCHAR(24) NOT NULL,
    `ORDER_ID` VARCHAR(36) NULL,
    `ORDER_ITEM_ID` VARCHAR(36) NULL,
    `SOURCE_PERIOD_ID` VARCHAR(36) NOT NULL,
    `CASH_PERIOD_ID` VARCHAR(36) NULL,
    `OCCURRED_AT` DATETIME(6) NOT NULL,
    `ALLOCATION_STATUS` VARCHAR(24) NOT NULL,
    `HOLD_SCOPE` VARCHAR(24) NOT NULL,
    `REASON` VARCHAR(500) NOT NULL,
    `REVERSES_RECORD_ID` VARCHAR(36) NULL,
    `CREATED_AT` DATETIME(6) NOT NULL,
    `CREATED_BY` VARCHAR(36) NOT NULL,
    `UPDATED_AT` DATETIME(6) NOT NULL,
    `UPDATED_BY` VARCHAR(36) NOT NULL,
    `CONFIRMED_AT` DATETIME(6) NULL,
    `CONFIRMED_BY` VARCHAR(36) NULL,
    PRIMARY KEY (`ID`),
    KEY `IX_ORDERING_FINANCE_RECORDS_SESSION` (`SESSION_ID`, `CREATED_AT`),
    KEY `IX_ORDERING_FINANCE_RECORDS_SOURCE` (`SOURCE_PERIOD_ID`, `ALLOCATION_STATUS`),
    KEY `IX_ORDERING_FINANCE_RECORDS_CASH` (`CASH_PERIOD_ID`, `OCCURRED_AT`),
    KEY `IX_ORDERING_FINANCE_RECORDS_ITEM` (`ORDER_ID`, `ORDER_ITEM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ORDERING_FINANCE_REVISIONS` (
    `RECORD_ID` VARCHAR(36) NOT NULL,
    `VERSION` BIGINT NOT NULL,
    `OPERATION_ID` VARCHAR(36) NOT NULL,
    `SNAPSHOT_JSON` LONGTEXT NOT NULL,
    `RECORDED_AT` DATETIME(6) NOT NULL,
    `RECORDED_BY` VARCHAR(36) NOT NULL,
    PRIMARY KEY (`RECORD_ID`, `VERSION`),
    KEY `IX_ORDERING_FINANCE_REVISIONS_OPERATION` (`OPERATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ORDERING_FINANCE_OPERATIONS` (
    `OPERATION_ID` VARCHAR(36) NOT NULL,
    `SESSION_ID` VARCHAR(36) NOT NULL,
    `PAYLOAD_HASH` CHAR(64) NOT NULL,
    `RESULT_JSON` LONGTEXT NOT NULL,
    `CREATED_AT` DATETIME(6) NOT NULL,
    `CREATED_BY` VARCHAR(36) NOT NULL,
    PRIMARY KEY (`OPERATION_ID`),
    KEY `IX_ORDERING_FINANCE_OPERATIONS_SESSION` (`SESSION_ID`, `CREATED_AT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
