-- Additive migration. Legacy commissions remain unassigned and hash-only.
-- No legacy code is rotated or reconstructed by this migration.
CREATE TABLE IF NOT EXISTS ART_DELIVERY_WORKFLOWS (
    DELIVERY_ID VARCHAR(36) NOT NULL PRIMARY KEY,
    ASSIGNED_STAFF_ID VARCHAR(40) NULL,
    CLAIM_CODE_ENCRYPTED TEXT NULL,
    NOTIFIED_AT DATETIME(6) NULL,
    NOTIFIED_BY VARCHAR(40) NULL,
    INDEX IX_DELIVERY_WORKFLOW_STAFF (ASSIGNED_STAFF_ID),
    CONSTRAINT FK_DELIVERY_WORKFLOW_DELIVERY FOREIGN KEY (DELIVERY_ID) REFERENCES ART_DELIVERIES(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
