-- Menu submission notification slice; no historical orders are enqueued.
CREATE TABLE IF NOT EXISTS NOTIFICATION_SETTINGS (
  OWNER_KEY VARCHAR(90) NOT NULL PRIMARY KEY,
  REVISION BIGINT NOT NULL DEFAULT 0,
  RULES_JSON LONGTEXT NOT NULL,
  UPDATED_AT DATETIME(6) NOT NULL,
  UPDATED_BY VARCHAR(40) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS NOTIFICATION_OUTBOX (
  ID VARCHAR(40) NOT NULL PRIMARY KEY,
  SOURCE_KEY VARCHAR(100) NOT NULL,
  PAYLOAD_JSON LONGTEXT NOT NULL,
  CREATED_AT DATETIME(6) NOT NULL,
  PROCESSED_AT DATETIME(6) NULL,
  UNIQUE KEY UQ_NOTIFICATION_SOURCE (SOURCE_KEY),
  KEY IX_NOTIFICATION_PENDING (PROCESSED_AT,CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS NOTIFICATION_DELIVERIES (
  ID VARCHAR(40) NOT NULL PRIMARY KEY,
  SOURCE_KEY VARCHAR(100) NOT NULL,
  RECIPIENT_ACCOUNT_ID VARCHAR(40) NOT NULL,
  PAYLOAD_JSON LONGTEXT NOT NULL,
  CREATED_AT DATETIME(6) NOT NULL,
  EXPIRES_AT DATETIME(6) NOT NULL,
  READ_AT DATETIME(6) NULL,
  UNIQUE KEY UQ_NOTIFICATION_RECIPIENT (SOURCE_KEY,RECIPIENT_ACCOUNT_ID),
  KEY IX_NOTIFICATION_INBOX (RECIPIENT_ACCOUNT_ID,CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS NOTIFICATION_AUDIT (
  ID VARCHAR(40) NOT NULL PRIMARY KEY,
  ACTOR_ACCOUNT_ID VARCHAR(40) NOT NULL,
  ACTION_TYPE VARCHAR(60) NOT NULL,
  ENTITY_ID VARCHAR(100) NOT NULL,
  BEFORE_JSON LONGTEXT NULL,
  AFTER_JSON LONGTEXT NULL,
  CREATED_AT DATETIME(6) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
