-- UID-only customer identity flow. Apply after 20260921_02_guestbook_identity_media.sql.
-- This migration keeps old credential columns nullable for compatibility, but the
-- application no longer issues or validates customer credentials.
ALTER TABLE CUSTOMER_PROFILES
  MODIFY COLUMN CREDENTIAL_HASH CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL;

ALTER TABLE CUSTOMER_ORDER_SESSIONS
  ADD COLUMN IF NOT EXISTS RECOVERY_CODE_ISSUED_AT DATETIME(6) NULL,
  ADD COLUMN IF NOT EXISTS RECOVERY_CODE_VERSION INT NOT NULL DEFAULT 1;

UPDATE CUSTOMER_ORDER_SESSIONS
SET RECOVERY_CODE_ISSUED_AT = COALESCE(RECOVERY_CODE_ISSUED_AT, UPDATED_AT, CREATED_AT),
    RECOVERY_CODE_VERSION = COALESCE(RECOVERY_CODE_VERSION, 1)
WHERE RECOVERY_CODE_ISSUED_AT IS NULL OR RECOVERY_CODE_VERSION IS NULL;
