-- Controlled production testing override for the ordering business-day resolver.
-- This table is intentionally soft-disabled; no DELETE is required.
CREATE TABLE IF NOT EXISTS `ORDERING_BUSINESS_DAY_OVERRIDE` (
    `ID` VARCHAR(36) NOT NULL,
    `BUSINESS_DATE` DATE NOT NULL,
    `STARTS_AT` DATETIME NOT NULL,
    `ENDS_AT` DATETIME NOT NULL,
    `EXPIRES_AT` DATETIME NOT NULL,
    `ENABLED` TINYINT(1) NOT NULL DEFAULT 1,
    `REASON` VARCHAR(500) NULL,
    `UPDATED_AT` DATETIME NOT NULL,
    `UPDATED_BY` VARCHAR(36) NULL,
    PRIMARY KEY (`ID`),
    KEY `IX_ORDERING_BUSINESS_DAY_OVERRIDE_ACTIVE` (`ENABLED`, `EXPIRES_AT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
