-- Additive, repeatable. Apply after 20260919_01. No existing session, order or cash data is changed.
-- UIDs identify; only credential hashes authorize. Never auto-merge GAME_ID/name matches.
-- Rollback: roll back application and retain these tables; no destructive rollback is required.
CREATE TABLE IF NOT EXISTS CUSTOMER_PROFILES (
 UID VARCHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 DISPLAY_NAME VARCHAR(100) NOT NULL,
 CREDENTIAL_HASH CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 CREDENTIAL_VERSION INT NOT NULL DEFAULT 1,
 CREATED_AT DATETIME(6) NOT NULL, UPDATED_AT DATETIME(6) NOT NULL,
 PRIMARY KEY (UID), UNIQUE KEY UX_CUSTOMER_CREDENTIAL (CREDENTIAL_HASH)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS CUSTOMER_VISITS (
 SESSION_ID VARCHAR(36) NOT NULL,
 CUSTOMER_UID VARCHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 LINKED_AT DATETIME(6) NOT NULL, LINKED_BY VARCHAR(36) NULL,
 PRIMARY KEY (SESSION_ID), KEY IX_CUSTOMER_VISITS_UID (CUSTOMER_UID,LINKED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS ART_DELIVERIES (
 ID VARCHAR(36) NOT NULL, SESSION_ID VARCHAR(36) NOT NULL,
 ORDER_ID VARCHAR(36) NULL, ORDER_ITEM_ID VARCHAR(36) NULL,
 TITLE VARCHAR(160) NOT NULL, DESCRIPTION VARCHAR(2000) NULL,
 STATUS VARCHAR(24) NOT NULL DEFAULT 'pending', DUE_DATE DATE NULL,
 CLAIM_CODE_HASH CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 VERSION INT NOT NULL DEFAULT 1, CREATED_AT DATETIME(6) NOT NULL, UPDATED_AT DATETIME(6) NOT NULL,
 CREATED_BY VARCHAR(36) NOT NULL, UPDATED_BY VARCHAR(36) NOT NULL, DELIVERED_AT DATETIME(6) NULL,
 PRIMARY KEY (ID), UNIQUE KEY UX_ART_DELIVERY_CLAIM (CLAIM_CODE_HASH),
 KEY IX_ART_DELIVERY_SESSION (SESSION_ID,CREATED_AT), KEY IX_ART_DELIVERY_STATUS (STATUS,UPDATED_AT),
 KEY IX_ART_DELIVERY_ORDER (ORDER_ID,ORDER_ITEM_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS ART_DELIVERY_ASSETS (
 ID VARCHAR(36) NOT NULL, DELIVERY_ID VARCHAR(36) NOT NULL,
 KIND VARCHAR(16) NOT NULL, LABEL VARCHAR(160) NOT NULL, URL VARCHAR(2048) NULL,
 CONTENT_TYPE VARCHAR(80) NULL, BYTE_SIZE INT NOT NULL DEFAULT 0, FILE_BYTES MEDIUMBLOB NULL,
 IS_REMOVED BOOLEAN NOT NULL DEFAULT FALSE, CREATED_AT DATETIME(6) NOT NULL, CREATED_BY VARCHAR(36) NOT NULL,
 PRIMARY KEY (ID), KEY IX_ART_ASSETS_DELIVERY (DELIVERY_ID,IS_REMOVED,CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS CUSTOMER_DELIVERY_AUDIT (
 ID VARCHAR(36) NOT NULL, ENTITY_TYPE VARCHAR(24) NOT NULL, ENTITY_ID VARCHAR(40) NOT NULL,
 ACTION VARCHAR(40) NOT NULL, ACTOR_ID VARCHAR(40) NULL, CREATED_AT DATETIME(6) NOT NULL,
 PRIMARY KEY (ID), KEY IX_CUSTOMER_DELIVERY_AUDIT_ENTITY (ENTITY_TYPE,ENTITY_ID,CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
