-- Customer room ordering: connect room bookings to customer orders while
-- keeping ROOM_SERVICE_ORDERS as the authoritative availability ledger.

ALTER TABLE `ROOM_SERVICE_ORDERS`
    ADD COLUMN IF NOT EXISTS `ORDER_ID` VARCHAR(36) NULL AFTER `ID`,
    ADD COLUMN IF NOT EXISTS `ORDER_ITEM_ID` VARCHAR(36) NULL AFTER `ORDER_ID`,
    ADD KEY IF NOT EXISTS `IX_ROOM_SERVICE_ORDERS_ORDER` (`ORDER_ID`),
    ADD KEY IF NOT EXISTS `IX_ROOM_SERVICE_ORDERS_ITEM` (`ORDER_ITEM_ID`);
