-- Customer ordering, nomination queue, tips and reporting snapshots.
-- The application intentionally enforces relationships in services/repositories;
-- this project does not use database foreign keys.

CREATE TABLE IF NOT EXISTS `ORDERING_SETTINGS` (
    `ID` VARCHAR(36) NOT NULL,
    `MINIMUM_MEAL_CREDIT` INT NOT NULL DEFAULT 0,
    `BASE_NOMINATION_FEE` INT NOT NULL DEFAULT 0,
    `SEGMENT_MINUTES` INT NOT NULL DEFAULT 20,
    `REMINDER_AFTER_MINUTES` INT NOT NULL DEFAULT 5,
    `ESCALATE_AFTER_MINUTES` INT NOT NULL DEFAULT 10,
    `EXPIRE_AFTER_MINUTES` INT NOT NULL DEFAULT 20,
    `NOMINATION_PAUSED_UNTIL` DATETIME NULL,
    `UPDATED_AT` DATETIME NOT NULL,
    `UPDATED_BY` VARCHAR(36) NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `ORDERING_SETTINGS`
    (`ID`, `MINIMUM_MEAL_CREDIT`, `BASE_NOMINATION_FEE`, `SEGMENT_MINUTES`,
     `REMINDER_AFTER_MINUTES`, `ESCALATE_AFTER_MINUTES`, `EXPIRE_AFTER_MINUTES`, `UPDATED_AT`)
VALUES ('default', 0, 0, 20, 5, 10, 20, NOW())
ON DUPLICATE KEY UPDATE `ID` = VALUES(`ID`);

CREATE TABLE IF NOT EXISTS `CUSTOMER_ORDER_SESSIONS` (
    `ID` VARCHAR(36) NOT NULL,
    `GAME_ID` VARCHAR(100) NOT NULL,
    `CUSTOMER_NAME` VARCHAR(100) NOT NULL,
    `BUSINESS_DATE` DATE NOT NULL,
    `ACCESS_TOKEN_HASH` CHAR(64) NOT NULL,
    `RECOVERY_CODE_HASH` CHAR(64) NOT NULL,
    `MAX_NOMINATED_STAFF` INT NOT NULL DEFAULT 1,
    `PREPAID_MEAL_CREDIT` INT NOT NULL DEFAULT 0,
    `REMAINING_MEAL_CREDIT` INT NOT NULL DEFAULT 0,
    `SESSION_STATUS` VARCHAR(24) NOT NULL DEFAULT 'active',
    `LAST_ACCESSED_AT` DATETIME NULL,
    `CREATED_AT` DATETIME NOT NULL,
    `CREATED_BY` VARCHAR(36) NULL,
    `UPDATED_AT` DATETIME NOT NULL,
    `UPDATED_BY` VARCHAR(36) NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UX_CUSTOMER_ORDER_SESSIONS_DAY_GAME` (`BUSINESS_DATE`, `GAME_ID`),
    UNIQUE KEY `UX_CUSTOMER_ORDER_SESSIONS_TOKEN` (`ACCESS_TOKEN_HASH`),
    KEY `IX_CUSTOMER_ORDER_SESSIONS_NAME` (`BUSINESS_DATE`, `CUSTOMER_NAME`),
    KEY `IX_CUSTOMER_ORDER_SESSIONS_STATUS` (`BUSINESS_DATE`, `SESSION_STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ORDERS` (
    `ID` VARCHAR(36) NOT NULL,
    `SESSION_ID` VARCHAR(36) NOT NULL,
    `ORDER_NUMBER` VARCHAR(32) NOT NULL,
    `ORDER_STATUS` VARCHAR(32) NOT NULL,
    `QUEUE_ENTERED_AT` DATETIME NULL,
    `SUBMITTED_AT` DATETIME NOT NULL,
    `CONFIRMED_AT` DATETIME NULL,
    `STARTED_AT` DATETIME NULL,
    `COMPLETED_AT` DATETIME NULL,
    `CANCELLED_AT` DATETIME NULL,
    `SUBTOTAL` INT NOT NULL DEFAULT 0,
    `MEAL_CREDIT_APPLIED` INT NOT NULL DEFAULT 0,
    `TOTAL_AMOUNT` INT NOT NULL DEFAULT 0,
    `CUSTOMER_NOTE` VARCHAR(500) NULL,
    `INTERNAL_NOTE` VARCHAR(1000) NULL,
    `CREATED_AT` DATETIME NOT NULL,
    `UPDATED_AT` DATETIME NOT NULL,
    `UPDATED_BY` VARCHAR(36) NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UX_ORDERS_NUMBER` (`ORDER_NUMBER`),
    KEY `IX_ORDERS_SESSION` (`SESSION_ID`, `SUBMITTED_AT`),
    KEY `IX_ORDERS_QUEUE` (`ORDER_STATUS`, `QUEUE_ENTERED_AT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ORDER_ITEMS` (
    `ID` VARCHAR(36) NOT NULL,
    `ORDER_ID` VARCHAR(36) NOT NULL,
    `ITEM_TYPE` VARCHAR(32) NOT NULL,
    `REFERENCE_ID` VARCHAR(36) NULL,
    `PARENT_ITEM_ID` VARCHAR(36) NULL,
    `NAME_SNAPSHOT` VARCHAR(160) NOT NULL,
    `UNIT_PRICE` INT NOT NULL,
    `QUANTITY` INT NOT NULL DEFAULT 1,
    `SEGMENT_COUNT` INT NULL,
    `DURATION_MINUTES` INT NULL,
    `LINE_TOTAL` INT NOT NULL,
    `PRICE_RULE` VARCHAR(32) NULL,
    `SORT_ORDER` INT NOT NULL DEFAULT 0,
    `CREATED_AT` DATETIME NOT NULL,
    `UPDATED_AT` DATETIME NOT NULL,
    `UPDATED_BY` VARCHAR(36) NULL,
    PRIMARY KEY (`ID`),
    KEY `IX_ORDER_ITEMS_ORDER` (`ORDER_ID`, `SORT_ORDER`),
    KEY `IX_ORDER_ITEMS_REFERENCE` (`REFERENCE_ID`),
    KEY `IX_ORDER_ITEMS_PARENT` (`PARENT_ITEM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ORDER_NOMINEES` (
    `ID` VARCHAR(36) NOT NULL,
    `ORDER_ID` VARCHAR(36) NOT NULL,
    `STAFF_ID` VARCHAR(36) NOT NULL,
    `STAFF_NAME_SNAPSHOT` VARCHAR(100) NOT NULL,
    `SERVICE_ID` VARCHAR(36) NOT NULL,
    `SERVICE_NAME_SNAPSHOT` VARCHAR(160) NOT NULL,
    `SEGMENT_COUNT` INT NOT NULL,
    `SERVICE_DURATION_MINUTES` INT NOT NULL,
    `REQUESTED_STARTS_AT` DATETIME NOT NULL,
    `REQUESTED_SERVICE_ENDS_AT` DATETIME NOT NULL,
    `REQUESTED_BUSY_UNTIL` DATETIME NOT NULL,
    `CONFIRMATION_STATUS` VARCHAR(24) NOT NULL DEFAULT 'waiting',
    `CONFIRMED_AT` DATETIME NULL,
    `CONFIRMED_BY` VARCHAR(36) NULL,
    `CREATED_AT` DATETIME NOT NULL,
    `UPDATED_AT` DATETIME NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UX_ORDER_NOMINEES_ORDER_STAFF` (`ORDER_ID`, `STAFF_ID`),
    KEY `IX_ORDER_NOMINEES_STAFF_QUEUE` (`STAFF_ID`, `CONFIRMATION_STATUS`, `REQUESTED_STARTS_AT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ORDER_TIPS` (
    `ID` VARCHAR(36) NOT NULL,
    `ORDER_ID` VARCHAR(36) NOT NULL,
    `ORDER_ITEM_ID` VARCHAR(36) NOT NULL,
    `STAFF_ID` VARCHAR(36) NULL,
    `STAFF_NAME_SNAPSHOT` VARCHAR(100) NULL,
    `TIP_AMOUNT` INT NOT NULL,
    `STAFF_PERCENTAGE` INT NOT NULL DEFAULT 0,
    `STORE_PERCENTAGE` INT NOT NULL DEFAULT 100,
    `STAFF_AMOUNT` INT NOT NULL DEFAULT 0,
    `STORE_AMOUNT` INT NOT NULL,
    `CREATED_AT` DATETIME NOT NULL,
    `UPDATED_AT` DATETIME NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UX_ORDER_TIPS_ITEM` (`ORDER_ITEM_ID`),
    KEY `IX_ORDER_TIPS_ORDER` (`ORDER_ID`),
    KEY `IX_ORDER_TIPS_STAFF` (`STAFF_ID`, `CREATED_AT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `STAFF_BUSY_BLOCKS` (
    `ID` VARCHAR(36) NOT NULL,
    `ORDER_ID` VARCHAR(36) NOT NULL,
    `ORDER_NOMINEE_ID` VARCHAR(36) NOT NULL,
    `STAFF_ID` VARCHAR(36) NOT NULL,
    `STARTS_AT` DATETIME NOT NULL,
    `SERVICE_ENDS_AT` DATETIME NOT NULL,
    `ENDS_AT` DATETIME NOT NULL,
    `BLOCK_STATUS` VARCHAR(24) NOT NULL DEFAULT 'active',
    `CREATED_AT` DATETIME NOT NULL,
    `UPDATED_AT` DATETIME NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UX_STAFF_BUSY_BLOCKS_NOMINEE` (`ORDER_NOMINEE_ID`),
    KEY `IX_STAFF_BUSY_BLOCKS_CONFLICT` (`STAFF_ID`, `BLOCK_STATUS`, `STARTS_AT`, `ENDS_AT`),
    KEY `IX_STAFF_BUSY_BLOCKS_ORDER` (`ORDER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ORDER_STATUS_HISTORY` (
    `ID` VARCHAR(36) NOT NULL,
    `ORDER_ID` VARCHAR(36) NOT NULL,
    `FROM_STATUS` VARCHAR(32) NULL,
    `TO_STATUS` VARCHAR(32) NOT NULL,
    `REASON` VARCHAR(500) NULL,
    `ACTOR_TYPE` VARCHAR(24) NOT NULL,
    `ACTOR_ID` VARCHAR(36) NULL,
    `CREATED_AT` DATETIME NOT NULL,
    PRIMARY KEY (`ID`),
    KEY `IX_ORDER_STATUS_HISTORY_ORDER` (`ORDER_ID`, `CREATED_AT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ORDER_AUDIT_LOG` (
    `ID` VARCHAR(36) NOT NULL,
    `ORDER_ID` VARCHAR(36) NULL,
    `SESSION_ID` VARCHAR(36) NULL,
    `ACTION_TYPE` VARCHAR(64) NOT NULL,
    `BEFORE_JSON` LONGTEXT NULL,
    `AFTER_JSON` LONGTEXT NULL,
    `ACTOR_ID` VARCHAR(36) NULL,
    `ACTOR_ROLE` VARCHAR(24) NULL,
    `CREATED_AT` DATETIME NOT NULL,
    PRIMARY KEY (`ID`),
    KEY `IX_ORDER_AUDIT_LOG_ORDER` (`ORDER_ID`, `CREATED_AT`),
    KEY `IX_ORDER_AUDIT_LOG_SESSION` (`SESSION_ID`, `CREATED_AT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Reporting reads these immutable order/item/tip snapshots directly. Views are
-- intentionally omitted because the production migration account does not own
-- DROP VIEW; historical values still remain independent of later menu edits.
