-- Apply explicitly with a migration-capable account before deploying the API.
-- Existing descriptions stay informational; no inferred product mapping or charges.
ALTER TABLE `PRICING_RULES` ADD COLUMN IF NOT EXISTS `POLICY_JSON` LONGTEXT NULL;
ALTER TABLE `MENU_ITEMS` ADD COLUMN IF NOT EXISTS `POLICY_JSON` LONGTEXT NULL;
ALTER TABLE `MENU_SETS` ADD COLUMN IF NOT EXISTS `POLICY_JSON` LONGTEXT NULL;
ALTER TABLE `ORDERS` ADD COLUMN IF NOT EXISTS `MENU_SNAPSHOT_JSON` LONGTEXT NULL;
CREATE TABLE IF NOT EXISTS `MENU_QUOTES` (
  `ID` VARCHAR(40) NOT NULL PRIMARY KEY,
  `SESSION_ID` VARCHAR(40) NOT NULL,
  `REQUEST_JSON` LONGTEXT NOT NULL,
  `SNAPSHOT_JSON` LONGTEXT NOT NULL,
  `FINGERPRINT` VARCHAR(64) NOT NULL,
  `EXPIRES_AT` DATETIME(6) NOT NULL,
  `ORDER_ID` VARCHAR(40) NULL,
  KEY `IX_MENU_QUOTES_SESSION` (`SESSION_ID`, `EXPIRES_AT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
