-- S11: transaction-ordered notification change log and cursor support.
-- Apply after 20260909_07_notification_repeats.sql.
CREATE TABLE IF NOT EXISTS `NOTIFICATION_CHANGE_CURSOR` (
    `ID` TINYINT NOT NULL PRIMARY KEY,
    `NEXT_SEQUENCE` BIGINT NOT NULL DEFAULT 0,
    `UPDATED_AT` DATETIME(6) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO `NOTIFICATION_CHANGE_CURSOR` (`ID`,`NEXT_SEQUENCE`,`UPDATED_AT`)
VALUES (1,0,NOW(6));

CREATE TABLE IF NOT EXISTS `NOTIFICATION_CHANGES` (
    `SEQUENCE` BIGINT NOT NULL,
    `CHANGE_ID` VARCHAR(40) NOT NULL,
    `RECIPIENT_ACCOUNT_ID` VARCHAR(40) NOT NULL,
    `DELIVERY_ID` VARCHAR(40) NULL,
    `CHANGE_TYPE` VARCHAR(40) NOT NULL,
    `PAYLOAD_JSON` LONGTEXT NOT NULL,
    `CREATED_AT` DATETIME(6) NOT NULL,
    PRIMARY KEY (`SEQUENCE`),
    UNIQUE KEY `UQ_NOTIFICATION_CHANGE_ID` (`CHANGE_ID`),
    KEY `IX_NOTIFICATION_CHANGE_RECIPIENT` (`RECIPIENT_ACCOUNT_ID`,`SEQUENCE`),
    KEY `IX_NOTIFICATION_CHANGE_CREATED` (`CREATED_AT`,`SEQUENCE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
